name: IAR Build Tools CI
on:
  push:
    branches: [ dev* ]
env:
  BUILD_TYPE: Debug  
  IARBUILD_PATH: "C:\\Program Files\\IAR Systems\\Embedded Workbench 9.0\\common\\bin\\iarbuild"
  IARBUILD_OPTS: -log all -parallel 2
jobs:
  iarbuild:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Get Location
        run: Get-Location
      - name: Build Library
        run: |
            echo $IARBUILD_PATH
        
        