name: CPPCheck
on:
  push:
    branches:
        - main
  workflow_dispatch:
    
jobs:
  cppcheck:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build CppCheck
        run: ./addons/run-cppcheck.bat
