name: CPPCheck
on:
  push:
    branches:
        - main
jobs:
  cppcheck:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build CppCheck
        run: ./run-cppcheck.bat