name: Doxygen
on:
  push:
    branches:
        - main
jobs:
  doxygen:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build Doxygen
        run: ./addons/run-doxygen.bat