name: IAR Build Tools CI
on:
  push:
    branches:
        - dev*
        - main
jobs:
  iarbuild:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build Library
        run: ./addons/compile_IAR.bat